### ISSUE TITLE
Updating the issues for project milestone sprint 2

### ISSUE THREAD

**Issue by n-idhi** [bcartwri96/chiia#15]
@acd1677 @anuragchiia @bcartwri-anu @Rajkamal24  Kindly update your issues with the progress made so far as we are approaching the semester 2 Sprint 2 Milestone. If anyone has question they can create an issue and label it as question. The concerned Team member will answer it within the time frame estimated.

**Comment by anuragchiia** [comment]
Ive just had issues with my dev env so far. because ive beeen migrating form using a virtual machine to having a dual boot setup. All fixed now thanks to ben.

**Comment by n-idhi** [comment]
Issues for the sprint 2 have been discussed and resolved
