### ISSUE TITLE
Task Creation

### ISSUE THREAD

**Issue by bcartwri-anu** [bcartwri96/chiia#18]

**Comment by n-idhi** [comment]
The task when assigned to analyst was not reflected in their view task.
The same can be viewed from https://docs.google.com/document/d/1X6wy-HTFc5a4VVEp3hsQR-czd0s5et_XH98m-IhouzM/edit#

**Comment by n-idhi** [comment]
The task has been assigned to the analyst which shows that the testing is done. The same can be viewed here https://docs.google.com/document/d/1X6wy-HTFc5a4VVEp3hsQR-czd0s5et_XH98m-IhouzM/edit#
