### ISSUE TITLE
Costings for Susan

### ISSUE THREAD

**Issue by bcartwri-anu** [bcartwri96/chiia#20]
Inc. scale-ability, cost at scale in terms of db and web dyno when @ production level

**Comment by bcartwri-anu** [comment]
@n-idhi have you done this?

**Comment by n-idhi** [comment]
I think we will do this in tomorrow's meeting with susan. She has called her technical handover analyst . I think i can have a discussion on the same with her.

**Comment by bcartwri-anu** [comment]
Done
